project_id = "swghcmyqracwifpdfyap"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000", "http://localhost:8080"]

[functions.workspace-management]
verify_jwt = true

[functions.document-management]
verify_jwt = true

[functions.document-content]
verify_jwt = true

[functions.permissions-management]
verify_jwt = true

[functions.public-document]
verify_jwt = false

[functions.public-diagram]
verify_jwt = false

[functions.crowdin-integration]
verify_jwt = true

[functions.yjs-sync]
verify_jwt = false

[functions.diagram-render]
verify_jwt = true